apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-kafka-1
  namespace: kafka
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    namespace: kafka
    name: data-kafka-1
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /kafka/kafka-1
    type: DirectoryOrCreate