apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-kafka-2
  namespace: kafka
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    namespace: kafka
    name: data-kafka-2
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /kafka/kafka-2
    type: DirectoryOrCreate