kind: Secret
apiVersion: v1
metadata:
  name: consumer-secret
  namespace: scraping
data:
  AWS_ACCESS_KEY_ID: eW91cl9hY2Nlc3M=
  AWS_SECRET_ACCESS_KEY: eW91cl9zZWNyZXQ=
  AWS_DEFAULT_REGION: YXAtbm9ydGhlYXN0LTI=
type: Opaque