apiVersion: apps/v1
kind: Deployment
metadata:
  name: eevl-experiment-deployment-wandb
  labels:
    app: eevl-experiment
    type: wandb
spec:
  template:
    metadata:
      name: eevl-experiment-pod
      labels:
        app: eevl-experiment
        type: wandb
    spec:
      containers:
      - name: wandb-container
        image: wandb/local
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      type: wandb