apiVersion: v1
kind: Service
metadata:
  name: eevl-experiment-service-wandb
  labels:
    app: eevl-experiment
spec:
  type: NodePort
  selector:
    app: eevl-experiment
    type: wandb
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
